name: "Private Actions Checkout"
description: "Enables using private actions on a workflow"
inputs:
  actions_list:
    description: List of private actions to checkout. Must be a JSON array and each entry must mutch the format owner/repo@ref
    required: false
    default: '["nedap/gha-deploy@master", "nedap/gha-build@master", "nedap/gha-notify-slack@master", "nedap/gha-yarn-cache@master", "nedap/gha-setup-timezone@master", "nedap/gha-repository-dispatch@master", "nedap/gha-environments@master"]'
  checkout_base_path:
    description: Where to checkout the custom actions
    required: true
    default: ./.github/actions
  ssh_private_key:
    description: If provided, configures the ssh-agent with the given private key.
    required: false
  app_id:
    description: The app id to authenticate with a GitHub app
    required: false
  app_private_key:
    description: The app private key to authenticate with a GitHub app
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'download-cloud'  
  color: 'yellow'
